version: "2.1"
services:
  mongodb1:
        image: mongo:latest
        restart: always
        container_name: mongodb1
        volumes:
        - mongodata1:/data/db
       
        expose:
        - "27017"
        ports:
        - 27011:27017
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
 
        networks:
            mynetwork:
              aliases:
               - mongodb

  mongodb2:
        image: mongo:latest
        restart: always
        container_name: mongodb2
        volumes:
        - mongodata2:/data/db
        expose:
        - "27017"
        ports:
        - 27012:27017
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

        networks:
            mynetwork:
              aliases:
               - mongodb

  mongodb3:
        image: mongo:latest
        restart: always
        container_name: mongodb3
        volumes:
        - mongodata3:/data/db
        expose:
        - "27017"
        ports:
        - 27013:27017
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all" ]  

        networks:
            mynetwork:
              aliases:
               - mongodb
 
  
networks:
  mynetwork:


volumes:
    mongodata1:
    mongodata2:
    mongodata3: 
